// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Task.Data;

#nullable disable

namespace Test.Task.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230620071536_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.Task.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("Quantiy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = "74.99",
                            Quantiy = "55",
                            Title = "HDD 1TB"
                        },
                        new
                        {
                            Id = 2,
                            Price = "109.99",
                            Quantiy = "102",
                            Title = " HDD SSD 512GB "
                        },
                        new
                        {
                            Id = 3,
                            Price = "80.99",
                            Quantiy = "47",
                            Title = " RAM DDR4 16GB"
                        },
                        new
                        {
                            Id = 4,
                            Price = "149.99",
                            Quantiy = "120",
                            Title = "SDD 1TB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
